kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: authelia-controller
subjects:
  - kind: ServiceAccount
    name: authelia-controller
roleRef:
  kind: ClusterRole
  name: authelia-controller
  apiGroup: rbac.authorization.k8s.io
