apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - ./crds.yaml
  - ./service-account.yaml
  - ./cluster-role.yaml
  - ./cluster-role-binding.yaml
  - ./deployment.yaml
