apiVersion: v1
kind: ServiceAccount
metadata:
  name: authelia-controller
  namespace: authelia
  labels:
    app: authelia-controller
    app.kubernetes.io/name: authelia-controller
automountServiceAccountToken: true
